seed: &seed 42
tasks:
  - livelier
  - more beautiful
  - more depressing
  - more boring
  - safer
  - wealthier
processor:
  _target_: transformers.AutoProcessor.from_pretrained
  pretrained_model_name_or_path: &pretrained_model_name_or_path facebook/dinov3-vitb16-pretrain-lvd1689m
  do_resize: false
backbone:
  _target_: transformers.AutoModel.from_pretrained
  pretrained_model_name_or_path: *pretrained_model_name_or_path
model_params:
  freeze_backbone: True

datasets:
  data_dir: &data_dir data/external/mit-place-pulse
  transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.ToTensor
        - _target_: grins.data.mit_place_pulse.preprocess.RemoveWatermark
          height: 277
  train_partial:
    _target_: grins.data.mit_place_pulse.dataset.MITPlacePulseDataset
    _partial_: true
    data_dir: *data_dir
    question: null
    seed: *seed
    split: train
  val_partial:
    _target_: grins.data.mit_place_pulse.dataset.MITPlacePulseDataset
    _partial_: true
    data_dir: *data_dir
    seed: *seed
    split: val
dataloaders:
  train_partial:
    _target_: torch.utils.data.DataLoader
    _partial_: true
    batch_size: 256
    shuffle: true
    num_workers: 8
  val_partial:
    _target_: torch.utils.data.DataLoader
    _partial_: true
    batch_size: 256
    shuffle: true
    num_workers: 8

loss_function_partial:
  _target_: grins.modeling.regress.model.TaskWeightedPairwiseRankingLoss
  _partial_: true
  use_task_weighting: true
optimizer_partial:
  _target_: torch.optim.AdamW
  _partial_: True
scheduler_name: constant_with_warmup

accelerator:
  _target_: accelerate.Accelerator
  project_dir: models/regress
num_epochs: 10
warmup_ratio: 0.2
