seed: &seed 42
tasks:
  - livelier
  - more beautiful
  - more depressing
  - more boring
  - safer
  - wealthier


processor:
  _target_: transformers.AutoImageProcessor.from_pretrained
  pretrained_model_name_or_path: facebook/dinov3-vitb16-pretrain-lvd1689m
  do_resize: false
backbone:
  _target_: grins.modeling.regress.random.IdentityBackbone

model_partial:
  _partial_: true
  _target_: grins.modeling.regress.random.RandomRegressor

datasets:
  data_dir: &data_dir data/external/mit-place-pulse
  transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.PILToTensor
        - _target_: grins.data.mit_place_pulse.preprocess.RemoveWatermark
          height: 277
  val_partial:
    _target_: grins.data.mit_place_pulse.dataset.MITPlacePulseDataset
    _partial_: true
    data_dir: *data_dir
    seed: *seed
    split: val
dataloaders:
  val_partial:
    _target_: torch.utils.data.DataLoader
    _partial_: true
    batch_size: 512
    shuffle: true
    num_workers: 8

loss_function_partial:
  _target_: grins.modeling.regress.TaskWeightedPairwiseLogisticRankingLoss
  _partial_: true
  use_task_weighting: false

project_dir: &project_dir out/regress/random
accelerator_partial:
  _target_: accelerate.Accelerator
  _partial_: true
  log_with: wandb
init_trackers_params:
  project_name: GRINS
